development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("redis://rediscloud:HXjEqnDtZkxBlBVDrf3XDUfmJpBhr1dg@redis-16726.c3.eu-west-1-1.ec2.cloud.redislabs.com:16726") { "redis://localhost:6379/1" } %>
  channel_prefix: jeu_de_mains_v2_production
