# config/meta.yml

# DEFAULT

meta_product_name: "Jeu de Mains"
meta_title: "Jeu de Mains | Offrez-vous un moment de détente créatif"
meta_description: "Réservez avec Jeu de Mains votre atelier créatif couture, céramique, cosmétique, herbier, broderie, tricot, bijoux… et découvrez les joies du faire soi-même !"
meta_keywords: "Jeu de Mains, ateliers créatifs. Do it yourself. Loisirs créatifs. Couture, céramique, cosmétique, herbier, broderie, tricot, peinture. Expérience insolite. Cadeau. Paris."
meta_image: "https://res.cloudinary.com/jeudemains/image/upload/v1601545768/jeu-de-mains-facebook-twitter.png"
meta_favicon: "https://res.cloudinary.com/jeudemains/image/upload/v1601583008/jeu-de-mains-favicon.png"
twitter_account: "@CoisneE"   # required for Twitter Cards
